language: bash
os:
  - linux
  - osx
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update && sudo apt-get install -y git-core; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew upgrade git; fi
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
script:
  - bats ./tests/
  - bash -i ./tests/suite.sh
