---
language: bash
os:
  - linux
  - osx

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:duggan/bats'
        packages:
          - bats
    packages:
      - bats
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - git
      - shellcheck
  homebrew:
    packages:
      - bats
      - git
      - python
      - python-pip
      - shellcheck
      - yamllint
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo pip install yamllint; fi

script:
  - bats ./tests/acceptance/
  - shellcheck -x bashlight
  - shellcheck -x *.bash
  - shellcheck -x **/*.bash
  - yamllint .

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  mkdir -p coverage &&
  kcov coverage bashlight &&
  bash <(curl -s https://codecov.io/bash)
