---
platform: linux
image_resource:
  type: docker-image
  source: {repository: vergissberlin/fedora-development}

inputs:
- name: resource-bashlib

outputs:
- name: test-result

run:
  path: sh
  args: ['./tests/tests.sh']
